---
all:
  hosts:
    gitlab-runner-01:
      ansible_host: 62.84.114.153
  #   nexus-01:
  #     ansible_host: 84.201.129.52
  children:
    gitlab-runers:
      hosts:
        gitlab-runner-01:

  #   nexus:
  #     hosts:
  #       nexus-01:
  #   postgres:
  #     hosts:
  #       sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos