
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

#services:
#  postgres:
#    image: 29ce379c6603
#    environment:
#      POSTGRES_DB: "test_db"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#      PGDATA: "/var/lib/postgresql/data/pgdata"

      #- .:/var/lib/postgresql/data
      #- .:/var/lib/postgresql/
#      ports:
#     - "5432:5432"
#     volumes:
#      - pgdata:/var/lib/postgresql/data
#      - pgconf:/etc/postgresql
#      - pglog:/var/log/postgresql
#
#volumes:
#  pgdata:
#    driver: local
#  pgconf:
#    driver: local
#  pglog:
#    driver: local
