# -*- mode: ruby -*-

ISO = "bento/ubuntu-20.04"
NET = "192.168.192."
DOMAIN = ".netology"
HOST_PREFIX = "teamcity"
INVENTORY_PATH = "../ansible/inventory"

servers = [
  {
    :hostname => HOST_PREFIX + "01" + DOMAIN,
    :ip => NET + "94",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :http_host => "8080",
    :http_vm => "8080",
    :teamcity_host => "8111",
    :teamcity_vm => "8111",
    :ram => 1024,
    :core => 1
      }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder "../..", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.network :forwarded_port, guest: machine[:http_vm], host: machine[:http_host]
      node.vm.network :forwarded_port, guest: machine[:teamcity_vm], host: machine[:teamcity_host]

#environment:
#SERVER_URL: "http://teamcity:8111"

      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
        #config.vm.provision :shell, :inline => "sudo apt-get update --fix-missing"
        config.vm.provision :shell, :inline => "sudo apt-get update"
        config.vm.provision :shell, :inline => "curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose"
        config.vm.provision :shell, :inline => "sudo chmod +x /usr/local/bin/docker-compose"
        config.vm.provision :shell, :inline => "docker-compose --version"
        #config.vm.provision :shell, :inline => "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
        #config.vm.provision :shell, :inline => 'sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"'
        #config.vm.provision :shell, :inline => "sudo apt-get install packer"
        #config.vm.provision :shell, :inline => "sudo apt-get install docker-compose-plugin=2.5.0"
      end
      #node.vm.provision "ansible" do |setup|
      #  setup.inventory_path = INVENTORY_PATH
      #  setup.playbook = "../ansible/provision.yml"
      #  setup.become = true
      #  setup.extra_vars = { ansible_user: 'vagrant' }
      #end
    end
  end
end
