# ---
# vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"

# vector_url2: "jopa"
# vector_version: 0.20.0
# # ----
# ansible_user_id: "centos"
# ansible_user_gid: "centos"
# # ----
# vector_config:
#   sources: 
#     our_log:   
#       type: file
#       ignore_older_secs: 600
#       include:
#       - /var/log/**/*.log
#       read_from: beginning
#   transforms:
#   sinks:
#     to_clickhouse:
#       type: clickhouse
#       inputs:
#         - our_log
#       database: custom
#       endpoint: http://51.250.64.225:8123
#       table: my_table
#       compression: gzip
#       healthcheck: false
#       skip_unknown_fields: true
