concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "shell-runner"
  url = "https://gitlab.com/"
  id = 17270267
  token = "m4RT_9tJJfKuAhDPiDaT"
  token_obtained_at = 2022-08-30T16:55:22Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
# /etc/gitlab-runner/config.toml